### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by filoozom** [ethersphere/bee-clef#16]
Hi,

I don't have a lot of information yet, but it appears that `clef's` RAM usage can quickly get out of control for no specific reason. As part of my 25 `bee` nodes on one server challenge, I often have to restart `clef` services because they consume up to 20 GB of RAM (I guess it could be more, but I didn't really want to find out).

It seems to happen when the `bee` containers are restarted while the `clef` ones are running, although I'm not sure about that.

Restart the services resolves the issue entirely for now.

**Comment by vandot** [comment]
@filoozom thanks for submitting this. All 25 bee nodes are using one single clef instance?

**Comment by filoozom** [comment]
> @filoozom thanks for submitting this. All 25 bee nodes are using one single clef instance?

No, one instance per `bee`. But I'm no longer running that many nodes, it's absolutely impossible due to https://github.com/ethersphere/bee/issues/1312.

**Comment by Eknir** [comment]
@atilla.lendvai

**Comment by attila-lendvai** [comment]
this will be resolved by https://github.com/ethersphere/bee-clef/pull/19

(@vandot i have no rights to close this issue)
