### ISSUE TITLE
Extremely high IO

### ISSUE THREAD

**Issue by filoozom** [ethersphere/bee-clef#18]
According to `docker stats`:

```
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
b6818110e6a1   swarm-2_bee_1    86.87%    5.457GiB / 62.82GiB   8.69%     1.14GB / 136MB    7.76GB / 59.2GB   33
1f0cd61ea368   swarm-1_bee_1    62.14%    4.779GiB / 62.82GiB   7.61%     917MB / 111MB     5.45GB / 61.5GB   30
a001af088548   swarm-0_bee_1    122.15%   7.407GiB / 62.82GiB   11.79%    1.17GB / 76.5MB   5.36GB / 83.2GB   27
```

For each of those `bee` nodes, there is a 50 to 70 times amplification from data ingested through network to disk writes. It looks like the node is constantly writing and deleting data, which causes an extremely high disk usage for a quite small amount of data.

**Comment by filoozom** [comment]
My bad, wrong repo: https://github.com/ethersphere/bee/issues/1312

**Comment by marvin-liu-sx** [comment]
Show your docker-compose file for a look
