### ISSUE TITLE
bee-clef down with success

### ISSUE THREAD

**Issue by iljooyoon** [ethersphere/bee-clef#24]
sometimes bee-clef down (when cashout or maybe resource problem), 

but it does not restart automatically, because clef down with success message.

so i should change bee-clef.service configuration from 'Restart=on-failure' to 'Restart=always'.

i think it is not good way because sometimes i could want to stop bee-clef.

**Comment by Eknir** [comment]
@vandot , what would be the best configuration that would ensure that `bee-clef` always restarts, unless the user explicitly turns it off?

**Comment by Eknir** [comment]
Thank you for reporting, we are looking into this!
