### ISSUE TITLE
FAILURE TO CONNECT TO CLEF SIGNER

### ISSUE THREAD

**Issue by rmourey26** [ethersphere/bee-clef#27]
![swarm_error_2](https://user-images.githubusercontent.com/20747769/116302632-6bfec800-a76f-11eb-8fcd-9b34a5c99301.PNG)

System---
Windows 10 Enterprise
WSL2 Docker back end
Ubuntu 20.04 WSL windows app AMD64
VS Code Insiders 1.56 
NVM 0.37
BASH TERMINAL
BEE-CLEF 4.10.0 (manual install)
BEE - 0.5.3 (manual install) 
![swarn_error](https://user-images.githubusercontent.com/20747769/116302144-d2371b00-a76e-11eb-81b9-9f92cac025a0.PNG)

***edit added second screenshot showing path format usage in Bee start config***attempted both with and without url=foo
***edit2 i just noticed I have the incorrect resolver syntax, should be braced [ "https://cloudflare-eth.com" ], now re-attempting connection***
***edit3 figured out IPC linkage but now clef is saying that the path of my ethereum keystore is not a directory and I know the path and keystore are in fact correct because as I mentioned, I had already created the account, attested to rules.js and successfully uploaded files to Ethereum before this update and I am using the same info that I previously saved***
**edit 4*** additionally I did experience the same issue described in issue #28 re-masterseed****I am unable to run bee nor clef at all at this point** 

I am not sure what occurred over the last few updates between CLEF 4.7 and BEE 4.9 up to now CLEF 4.10 & BEE 0.5.3 but I did not have this issue before the updates, I could run swarm and upload test files no problem at all. And now I have this. Even on my Linux only PC, I have a similar issue but thats for another post. The error is described below..

Bee is pointed directly to CLEFs ipc endpoint, "/home/usrname/.clef/clef.ipc" yet cannot find the endpoint. I imagine I need to instruct SUDO somewhere in config? Bee now has account/user auto setups but what are happening with those that already created accounts, checquebooks, backups and have been running nodes? Where are the instructions for proper integration? Website says to look at "all the files to be found in the bee-clef repository" without any explanation on actual implementation. Perhaps the docss are in the process of being updated now considering this update just occurred. But I am one frustrated coder who., after 9 plus months of developing 15 hours a day, finally went to deploy his DApp today via Swarm and ran into seemingly unnecessary issues. But this is what makes our job so great right? :-) Thanks in advance! Big fan of swarm and the hard work you all do! Please let me know if you need more system details! I am thinking it may be best to deploy from Linux and or Docker rather then WSL2. If you need more details, please let me know!

**Comment by Eknir** [comment]
Hi there, thanks for trying out Bee!

It is best if you ask in our support group on Discord: https://discord.gg/QpVwzJ3JKj

We gladly help you there.

**Comment by Eknir** [comment]
Hi @rmourey26 and @FengShaduVIP , how is it going on this issue? Was it resolved?
With hindsight, I think I was a bit too rigorous, closing this issue. I would be very happy to hear from you if the issue was already resolved, and if not, we can reopen this issue and have a closer look into it.
Thanks

**Comment by vandot** [comment]
@rmourey26 it looks like that you specified `home` and not `/home` to bee
