### ISSUE TITLE
为什么挖不到票?

### ISSUE THREAD

**Issue by jiang29717** [ethersphere/bee-clef#29]
Network normal link, bandwidth is 500m, computer configuration is very high, hard disk storage 1t. Network test node has 100, where the problem?

**Comment by westzhou666** [comment]
so am i

**Comment by Eknir** [comment]
Hey, I don't really understand what you mean. Could you elaborate please?

In any case, this seems to me not a bug, but a request for support. We are happy to help you in our [Discord](https://discord.gg/A6SBuEaK)
