### ISSUE TITLE
HELP:How to solve this problem?

### ISSUE THREAD

**Issue by Joky-yuci** [ethersphere/bee-clef#33]
I close the clef and bee when i can't cashout the  cheque.
when i open the clef and bee again ,it happy:
![image](https://user-images.githubusercontent.com/82747202/118672463-d795fb80-b82a-11eb-954f-3c17a6af22fb.png)
Infomation like this:
INFO[2021-05-18T10:40:03-04:00] could not connect to backend at https://rpc.slock.it/goerli?. In a swap-enabled network a working blockchain node (for goerli network in production) is required. Check your node or specify another node using --swap-endpoint. 
Error: get chain id: Post "https://rpc.slock.it/goerli?": EOF

**Comment by attila-lendvai** [comment]
the specified ethereum node is unreachable. read the docs, or wait until it comes back online.
