### ISSUE TITLE
Get "Error: init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused" when running bee service

### ISSUE THREAD

**Issue by adrianzhang** [ethersphere/bee-clef#39]
Hi there,

I'v installed bee-clef and bee by following official guide https://docs.ethswarm.org/docs/installation/install.

The status of bee-clef in systemd is activate and good.

Once I run bee service, log shows the error Error: init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused.

I googled the error, and it looks like clef problem.
I did check the configure file which is /etc/bee-clef/bee-config.yaml, there is no useful info since it is default one (also there is no step to configure it in the official guide).
I did netstat to check port status, no process listen on 8546.

So I think there should be some mistake in service config or official guide.

Any advice? Thanks in advance.

**Comment by adrianzhang** [comment]
The reason is that default endpoint setting in configuration of bee.yaml doesn't work. follow the guide to make api and pasted.

**Comment by ksang77** [comment]
i'm hitting same error, may i know how did you fixed it, can you share the guide.

**Comment by attila-lendvai** [comment]
@ksang77 see blockchain endpoint at https://docs.ethswarm.org/docs/installation/install#configure-bee
