### ISSUE TITLE
Export ethereum keys

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee-clef#4]
## Story
As a user of bee-clef, I want to import my bee-clef keys into external wallets, such that I can spend the BZZ which I earned through Swarm

## Background
I just found out that I can't cd into the /var/lib/bee-clef directory and hence don't know how to access my key files. It would perhaps be nice to have some sort of tooling that would read the keys and print them to the terminal (if this is secure). Additionally, there needs to be documentation (walk through style) which helps the user on migrating their bee-clef keys into a wallet like Metamask

**Comment by vandot** [comment]
@Eknir what needs to be exported key in json format and password?

How to export, place files in some defined directory?

**Comment by Eknir** [comment]
@vandot please have a look at how Metamask does it. There, you can import a JSON file with a password. 
The user should have an easy way to get these.

About the exact standard of the JSON they use, I'm not entirely sure, but I could find this: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition . I think Ralph can help you here if for whatever reason your JSON is not compatible with the standard.

About how/where to export, I'm not having an opinion. As long as it is easy and understandable to the user how to get it and it should not put the security of the keys at risk. If this user story cannot be  completed without a big degradation in security, then we can also consider to just properly document how the user can already get to the information now.

**Comment by Eknir** [comment]
@vandot , please leave the issue open and drag it to the appropriate column in the review workspace. From there, the issue will float to the QA and documentation workspaces. Thanks.
