### ISSUE TITLE
help: How to use bee-clef-windows-amd64.exe?

### ISSUE THREAD

**Issue by Hallkong** [ethersphere/bee-clef#41]
How to use bee-clef in windows？

**Comment by attila-lendvai** [comment]
windows is not supported yet.

please ask support questions on discord: https://discord.gg/GU22h2utj6
and/or read the documentation at: https://docs.ethswarm.org/

(@vandot FYI, i have no permission to close issues)

**Comment by attila-lendvai** [comment]
you may also consider running your node without clef on windows.

**Comment by Hallkong** [comment]
> windows is not supported yet.
> 
> please ask support questions on discord: https://discord.gg/GU22h2utj6
> and/or read the documentation at: https://docs.ethswarm.org/
> 
> (@vandot FYI, i have no permission to close issues)

So, what's the purpose for the bee-clef-windows-amd64.exe?
