### ISSUE TITLE
invalid chain id , xdai chainid change

### ISSUE THREAD

**Issue by code-scan** [ethersphere/bee-clef#42]
/bee-clef/packaging/bee-clef-service
must change 
```
CHAINID=5
```
to
```
CHAINID=100
```
## ubuntu
change file /usr/bin/bee-clef-service

```
CHAINID=5
```
to
```
CHAINID=100
```

## run
```
service bee-clef restart
```

enjoy your bee client !

https://www.pocpool.io/

**Comment by vandot** [comment]
@code-scan by default bee connect to [testnet](https://github.com/ethersphere/bee/blob/1fc07169dcc002944d075f406c9bf1e8b7ec66a9/cmd/bee/cmd/cmd.go#L215) thats why default is 5 (goerli network)
`bee-clef-service` reads ENV variable [BEE_CLEF_CHAIN_ID](https://github.com/ethersphere/bee-clef/blob/master/packaging/bee-clef-service#L18) to set diff chain_id if needed
