### ISSUE TITLE
dpkg: error processing package bee-clef (--install):  installed bee-clef package post-installation script subprocess returned error exit status 1 Errors were encountered while processing:  bee-clef

### ISSUE THREAD

**Issue by gitcoinkuang** [ethersphere/bee-clef#43]
dpkg: error processing package bee-clef (--install):
 installed bee-clef package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 bee-clef

**Comment by attila-lendvai** [comment]
without more information we cannot do much. we need some logs, exact version of the bee-clef package and the OS used, etc.
