### ISSUE TITLE
latest v0.5.0 CHAINID - invalid

### ISSUE THREAD

**Issue by TowayWei** [ethersphere/bee-clef#45]
bee-clef/packaging/bee-clef.service

[Service]
EnvironmentFile=-/etc/default/bee-clef

needs to remove "-"

**Comment by attila-lendvai** [comment]
> needs to remove "-"

why?

AFAIK, `-` there means that the file is optional; i.e. it communicates to systemd not to fail when the file is missing.

and on e.g. NixOS that file is not used (missing).
